json.id contact.id
json.first_name contact.first_name
json.middle_name contact.middle_name
json.last_name contact.last_name
json.email contact.email
json.time contact.friendly_created_at
json.full_name contact.full_name
json.bio contact.bio
json.user_id contact.user_id
